services:
  db:
    image: "postgres:17"
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: ["./pg17_data:/var/lib/postgresql/data"]

  web:
    depends_on: ["db"]
    image: "benoitmc/minifeed"
    restart: unless-stopped
    environment:
      POSTGRESQL_HOST: db
      POSTGRESQL_USER: postgres
      SECRET_KEY_BASE: 0 # change me
    ports:
      - "3000:3000"
