default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test: &test
  <<: *default
  database: db/test.sqlite3

production: &production
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["POSTGRESQL_DB"] %>
  pool: 5
  host: <%= ENV["POSTGRESQL_HOST"] %>
  username: <%= ENV["POSTGRESQL_USER"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>

staging:
  <<: *production

cucumber:
  <<: *test
