default: &default
  adapter: postgresql
  encoding: unicode
  pool: 32
  host: <%= ENV["POSTGRESQL_HOST"] || "localhost" %>
  database: <%= ENV["POSTGRESQL_DB"] || Rails.app_env_id %>
  username: <%= ENV["POSTGRESQL_USER"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>

development:
  <<: *default

test: &test
  <<: *default

production: &production
  <<: *default

staging:
  <<: *production
