name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: benoitmc/ci-rails

    steps:
    - uses: actions/checkout@v2
    - run: source rails-setup && test-all
