name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.4

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2

    - run: |
      export POSTGRES_HOST=postgres
      bundle install -j 5
      bundle exec rake db:create db:schema:load
      bundle exec rubocop
      bundle exec rspec
      bundle exec cucumber
